name: Ensure the PR template has been modified

on:
  pull_request:
    types: [edited, synchronize, ready_for_review]
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Verify PR Template is filled out
      uses: foursquare/pr-template-fillout-verifier@v1.0.2
