name: Ensure the PR template has been modified

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to run check on'
        required: true

jobs:
  check-pr-template:
    name: PR Template Verification
    runs-on: ubuntu-latest

    steps:
    - name: Get PR body and validate it
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = Number('${{ inputs.pr_number }}');

          if (!prNumber || isNaN(prNumber)) {
            core.setFailed("❌ Invalid PR number.");
            return;
          }

          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          const body = pr.body;

          if (!body) {
            core.setFailed("❌ PR description is empty. Please fill out the PR template.");
            return;
          }

          const incompleteMarkers = [
            "<!-- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. -->",
            "<!-- Jira task num -->",
            "<!-- Please describe the tests that you ran to verify your changes. Provide reproducible instructions. Please also list any relevant details for your test configuration. -->",
            "- [ ] My code follows the style guidelines of this project",
            "- [ ] I have performed a self-review of my own code",
            "- [ ] I have commented my code, particularly in hard-to-understand areas",
            "- [ ] I have made corresponding changes to the documentation",
            "- [ ] My changes generate no new warnings",
            "- [ ] I have added tests that prove my fix is effective or that my feature works",
            "- [ ] Any dependent changes have been merged and published in downstream modules"
          ];

          const missingSections = incompleteMarkers.filter(marker => body.includes(marker));

          if (missingSections.length > 0) {
            core.setFailed(`❌ PR template is incomplete. Please address the following:\n${missingSections.join('\n')}`);
          } else {
            console.log("✅ PR template looks complete.");
          }
