name: Ensure the PR template has been modified

on:
  # Automatically run on PR events so GitHub can report status to the PR
  pull_request:
    types: [opened, edited, reopened, synchronize]

  # Also support manual triggering
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to run check on (only needed for manual runs)'
        required: false

jobs:
  check-pr-template:
    name: PR Template Verification
    runs-on: ubuntu-latest

    steps:
    - name: Determine PR number
      id: find_pr
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "PR_NUM=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
        else
          echo "PR_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
        fi

    - name: Validate PR template
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = Number('${{ steps.find_pr.outputs.PR_NUM }}');

          if (!Number.isInteger(prNumber) || prNumber <= 0) {
            core.setFailed("❌ Invalid PR number.");
            return;
          }

          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          const body = pr.body;

          if (!body) {
            core.setFailed("❌ PR description is empty. Please fill out the PR template.");
            return;
          }

          const incompleteMarkers = [
            "<!-- Please include a summary of the change and which issue is fixed. Please also include relevant motivation
