name: Ensure the PR template has been modified

on:
  workflow_dispatch: # This must be run manually
  inputs:
      pr_branch:
        description: 'PR branch to run check on'
        required: true

jobs:
  check-pr-template:
      name: PR Template Verification
      runs-on: ubuntu-latest

      steps:
        - name: Verify PR Template is filled out
          uses: foursquare/pr-template-fillout-verifier@v1.0.2