# This workflow will install Python dependencies, run ruff and lint with a variety of Python versions
# For more information see: https://github.com/astral-sh/ruff-action

name: Run Python Ruff

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Auto format with ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --line-length=100"
    - name: Commit Ruff formatting changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Apply Ruff formatting" || echo "No changes to commit"
        git push

